name: Vitest Unittests

defaults:
    run:
        working-directory: ./src

on:
    pull_request:
        paths:
            - "src/**"
        branches: main

jobs: # Source for parts of this job: https://www.the-koi.com/projects/setting-up-a-superfast-ci-with-vitest-and-github-actions/
    unittests:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Install dependencies
              run: npm ci
            - name: Run Vitest tests
              run: npm run test:unit
