name: Vitest Unittests

defaults:
  run:
    working-directory: ./src

on:
  pull_request:
    branches: main

jobs: # Source for parts of this job: https://www.the-koi.com/projects/setting-up-a-superfast-ci-with-vitest-and-github-actions/
  unittests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Execute Unit tests
      - run: npm ci
	    - run: npm run test:unit
